services:
  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:v23.2.14
    container_name: redpanda
    command:
      - redpanda start
      - --smp 1
      - --memory 1G
      - --reserve-memory 0M
      - --overprovisioned
      - --node-id 0
      - --check=false
      - --kafka-addr PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      - --advertise-kafka-addr PLAINTEXT://redpanda:29092,OUTSIDE://localhost:9092
    ports:
      - "9092:9092"
      - "9644:9644"

  redpanda-console:
    image: docker.redpanda.com/redpandadata/console:v2.3.8
    container_name: redpanda-console
    environment:
      KAFKA_BROKERS: redpanda:29092
    ports:
      - "8082:8080"
    depends_on:
      - redpanda

  producer:
    build:
      context: ../../apps/ingest
      dockerfile: Dockerfile
    container_name: producer
    environment:
      REDPANDA_BROKERS: redpanda:29092
      DATASET_PATH: /data/online_retail_II.xlsx
    volumes:
      - ../../data/raw_datasets/online_retail_II.xlsx:/data/online_retail_II.xlsx:ro
    depends_on:
      - redpanda
    restart: on-failure

  minio:
    image: minio/minio:RELEASE.2023-10-16T04-13-43Z
    container_name: minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ../../data/minio:/data

  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: streamforge
    ports:
      - "5432:5432"
    volumes:
      - ../../data/postgres:/var/lib/postgresql/data
      - ../../ops/postgres:/docker-entrypoint-initdb.d

  trino:
    image: trinodb/trino:432
    container_name: trino
    ports:
      - "8081:8080" # Updated to avoid port 8080 conflict
    volumes:
      - ../../ops/trino/etc:/etc/trino
      - ../../data/trino-catalog:/data/hive-catalog
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/v1/info" ]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ../../apps/api
      dockerfile: Dockerfile
    container_name: api
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: "5432"
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: streamforge
      TRINO_HOST: trino
      TRINO_PORT: "8080"
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - trino

  web:
    build:
      context: ../../apps/web
      dockerfile: Dockerfile
    container_name: web
    ports:
      - "3000:80"
    depends_on:
      - api
